name: Test

on:
  workflow_dispatch:
  push:
    branches: 
      - "**"

jobs:
  main:
    runs-on: windows-latest
    steps:
    
    - name: a
      run: |
        curl -LO https://aka.ms/vs/17/release/vs_community.exe
        .\vs_community.exe --quiet --wait --norestart --nocache ^
          --installPath C:\o ^
          --add Microsoft.VisualStudio.Workload.NativeDesktop ^
          --add Microsoft.VisualStudio.Component.Windows10SDK.22621 ^
          --includeRecommended ^
          --passive
      shell: cmd
    - name: b
      uses: actions/upload-artifact@v4
      with: 
        path: C:\o
        name: vs